export const ADDANSWERREQUEST = 'ADDANSWERREQUEST';
export const ADDANSWERSUCCESS = 'ADDANSWERSUCCESS';
export const ADDANSWERFAIL = 'ADDANSWERFAIL';
export const ADDANSWERCLEARERROR = 'ADDANSWERCLEARERROR';