export const ADDQUESTIONREQUEST = 'ADDQUESTIONREQUEST';
export const ADDQUESTIONSUCCESS = 'ADDQUESTIONSUCCESS';
export const ADDQUESTIONFAIL = 'ADDQUESTIONFAIL';
export const ADDQUESTIONCLEARERROR = 'ADDQUESTIONCLEARERROR';