export const ALLANSWERREQUEST = 'ALLANSWERREQUEST';
export const ALLANSWERSUCCESS = 'ALLANSWERSUCCESS';
export const ALLANSWERFAIL = 'ALLANSWERFAIL';
export const ALLANSWERCLEARERROR = 'ALLANSWERCLEARERROR';