export const ALLQUESTIONREQUEST = 'ALLQUESTIONREQUEST';
export const ALLQUESTIONSUCCESS = 'ALLQUESTIONSUCCESS';
export const ALLQUESTIONFAIL = 'ALLQUESTIONFAIL';
export const ALLQUESTIONCLEARERROR = 'ALLQUESTIONCLEARERROR';